---

- hosts: all
  become: yes
  become_user: root
  vars_files:
    - ./var.yml
  tasks:

    - name: Create a ext4 filesystem on /dev/xvdb
      filesystem:
        fstype: ext4
        dev: /dev/xvdb

    - name: Ensure backup directory exist
      file:
        path: /var_backup
        state: directory

    - name: Backup /var directory
      shell:
        cmd: cp -ax * /var_backup
        chdir: /var

    - name: Ensure separated ebs is mounted on /var
      mount:
        path: /var
        src: /dev/xvdb
        state: mounted
        fstype: ext4

    - name: Restore /var directory content
      shell:
        cmd: cp -ax * /var
        chdir: /var_backup

    - name: Ensure /var backup is removed
      file:
        path: /var_backup
        state: absent

    - name: Ensure that necessary packages are installed
      yum:
        name:
          - epel-release 
          - git 
          - ansible
        state: latest

    - name: Packer installation 
      unarchive:
        src: https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
