credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: "jenkins-ssh-private-key"
              username: "jenkins"
              description: "Jenkins SSH Private key"
              privateKeySource:
                directEntry:
                  privateKey: "{{ jenkins_ssh_private_key }}"

          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: "gitlab-ssh-private-key-readonly-access"
              username: "jenkins-master-readonly"
              description: "Gitlab readonly SSH private key"
              privateKeySource:
                directEntry:
                  privateKey: "{{ gitlab_readonly_private_key }}"
                  
          - aws:
              scope: GLOBAL
              id: "terraform-executor"
              accessKey: "{{ terraform_executor_aws_access_key_id }}"
              secretKey: "{{ terraform_executor_aws_secret_access_key }}"
              description: "User for terraform code execution"
          - aws:
              scope: GLOBAL
              id: "packer-executor"
              accessKey: "{{ packer_executor_aws_access_key_id }}"
              secretKey: "{{ packer_executor_aws_secret_access_key }}"
              description: "User for packer builds execution"