- name: test
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Upgrade all packages
      get_url:
        url: https://files.phpmyadmin.net/phpMyAdmin/4.9.4/phpMyAdmin-4.9.4-all-languages.zip
        dest: /var/www/html

        
    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /var/www/html/phpMyAdmin-4.9.4-all-languages.zip
        dest: /var/www/html/phpMyAdmin
        remote_src: yes